# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
"""Render explicit generic-forwarder CI routes; no dynamic Collector pipelines."""
import argparse
import json
from pathlib import Path
import yaml

ROUTES = {
    "/api/v2/citestcycle": "citestcycle-intake",
    "/api/v2/citestcov": "citestcov-intake",
    "/api/v2/cicovreprt": "ci-intake",
    "/api/v2/libraries/tests/services/setting": "api",
    "/api/v2/ci/tests/skippable": "api",
    "/api/v2/ci/libraries/tests": "api",
    "/api/v2/ci/libraries/tests/flaky": "api",
    "/api/v2/test/libraries/test-management/tests": "api",
    "/api/v2/git/repository/search_commits": "api",
    "/api/v2/git/repository/packfile": "api",
}


def configuration(enabled=True):
    config = yaml.safe_load((Path(__file__).parent / "collector.yaml").read_text())
    forwarder = {
        "ingress": {"endpoint": "0.0.0.0:8126", "compression_algorithms": []},
        "egress": {"endpoint": "https://api.${env:DD_SITE}"},
        "routes": [{"path": "/info", "method": "GET", "response": {"status": 200,
                    "headers": {"Content-Type": "application/json"},
                    "body": json.dumps({"endpoints": ["/evp_proxy/v2/", "/evp_proxy/v4/"] if enabled else [],
                                        "config": {"default_env": "ddot-poc"}})}}],
    }
    for version in ("v2", "v4"):
        for path, subdomain in ROUTES.items():
            forwarder["routes"].append({
                "path": "/evp_proxy/" + version + path, "method": "POST", "disabled": not enabled,
                "match_headers": {"X-Datadog-EVP-Subdomain": subdomain},
                "endpoint": "https://" + subdomain + ".${env:DD_SITE}" + path,
                "headers": {"DD-API-KEY": "${env:DD_API_KEY}", "X-Datadog-Hostname": "${env:DD_HOSTNAME}",
                            "X-Datadog-AgentDefaultEnv": "ddot-poc", "X-Datadog-Additional-Tags": "env:ddot-poc"},
                "remove_headers": ["Authorization", "DD-APPLICATION-KEY", "Cookie", "X-Datadog-EVP-Subdomain",
                                   "X-Datadog-NeedsAppKey", "X-Forwarded-For", "X-Forwarded-Host", "X-Forwarded-Proto"],
            })
    config["extensions"] = {"http_forwarder": forwarder}
    config["service"]["extensions"] = ["http_forwarder"]
    return config


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--disabled", action="store_true")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    Path(args.output).write_text("# Generated by configure.py; real Datadog destinations only.\n" +
                                 yaml.safe_dump(configuration(not args.disabled), sort_keys=False))
