# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: batch/v1
kind: Job
metadata:
  name: ci-python-datadog-extension
  namespace: ddot-poc
  labels:
    app.kubernetes.io/part-of: ddot-products-poc
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: ci-python-datadog-extension
        app.kubernetes.io/part-of: ddot-products-poc
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: otel-dd-worker
      containers:
        - name: workload
          image: ddot-ci-python:poc
          imagePullPolicy: Never
          env:
            - name: DD_TRACE_AGENT_URL
              value: http://collector.ddot-poc.svc.cluster.local:8126
            - name: DD_SERVICE
              value: ddot-ci-python-datadog-extension
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ci-python-http-forwarder
  namespace: ddot-poc
  labels:
    app.kubernetes.io/part-of: ddot-products-poc
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: ci-python-http-forwarder
        app.kubernetes.io/part-of: ddot-products-poc
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: otel-dd-worker
      containers:
        - name: workload
          image: ddot-ci-python:poc
          imagePullPolicy: Never
          env:
            - name: DD_TRACE_AGENT_URL
              value: http://collector-http-forwarder.ddot-poc.svc.cluster.local:8126
            - name: DD_SERVICE
              value: ddot-ci-python-http-forwarder
