// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("telltailmetrics")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/connector/telltailmetricsconnector"
)

const (
	TracesToMetricsStability = component.StabilityLevelAlpha
	TracesToTracesStability  = component.StabilityLevelAlpha
)
