// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Taken from dd-source/domains/evp-workers/libs/rust/evp-workers-runtime/proto/wide_telemetry.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: exporter/datadogwideexporter/internal/widepb/wide_telemetry.proto

package widepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableKind int32

const (
	TableKind_TABLE_KIND_UNSPECIFIED TableKind = 0
	TableKind_TABLE_KIND_AGGREGATED  TableKind = 1
	TableKind_TABLE_KIND_SAMPLED     TableKind = 2
)

// Enum value maps for TableKind.
var (
	TableKind_name = map[int32]string{
		0: "TABLE_KIND_UNSPECIFIED",
		1: "TABLE_KIND_AGGREGATED",
		2: "TABLE_KIND_SAMPLED",
	}
	TableKind_value = map[string]int32{
		"TABLE_KIND_UNSPECIFIED": 0,
		"TABLE_KIND_AGGREGATED":  1,
		"TABLE_KIND_SAMPLED":     2,
	}
)

func (x TableKind) Enum() *TableKind {
	p := new(TableKind)
	*p = x
	return p
}

func (x TableKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableKind) Descriptor() protoreflect.EnumDescriptor {
	return file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_enumTypes[0].Descriptor()
}

func (TableKind) Type() protoreflect.EnumType {
	return &file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_enumTypes[0]
}

func (x TableKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableKind.Descriptor instead.
func (TableKind) EnumDescriptor() ([]byte, []int) {
	return file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDescGZIP(), []int{0}
}

type WideTelemetryEnvelope struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Host               string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Service            string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	FlushWindowStartMs uint64                 `protobuf:"varint,7,opt,name=flush_window_start_ms,json=flushWindowStartMs,proto3" json:"flush_window_start_ms,omitempty"`
	FlushWindowEndMs   uint64                 `protobuf:"varint,8,opt,name=flush_window_end_ms,json=flushWindowEndMs,proto3" json:"flush_window_end_ms,omitempty"`
	Tables             []*WideTable           `protobuf:"bytes,9,rep,name=tables,proto3" json:"tables,omitempty"`
	Tags               map[string]string      `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WideTelemetryEnvelope) Reset() {
	*x = WideTelemetryEnvelope{}
	mi := &file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WideTelemetryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WideTelemetryEnvelope) ProtoMessage() {}

func (x *WideTelemetryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WideTelemetryEnvelope.ProtoReflect.Descriptor instead.
func (*WideTelemetryEnvelope) Descriptor() ([]byte, []int) {
	return file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *WideTelemetryEnvelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WideTelemetryEnvelope) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *WideTelemetryEnvelope) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WideTelemetryEnvelope) GetFlushWindowStartMs() uint64 {
	if x != nil {
		return x.FlushWindowStartMs
	}
	return 0
}

func (x *WideTelemetryEnvelope) GetFlushWindowEndMs() uint64 {
	if x != nil {
		return x.FlushWindowEndMs
	}
	return 0
}

func (x *WideTelemetryEnvelope) GetTables() []*WideTable {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *WideTelemetryEnvelope) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type WideTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Kind          TableKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=datadog.evp.wide.TableKind" json:"kind,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,3,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	ArrowIpc      []byte                 `protobuf:"bytes,4,opt,name=arrow_ipc,json=arrowIpc,proto3" json:"arrow_ipc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WideTable) Reset() {
	*x = WideTable{}
	mi := &file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WideTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WideTable) ProtoMessage() {}

func (x *WideTable) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WideTable.ProtoReflect.Descriptor instead.
func (*WideTable) Descriptor() ([]byte, []int) {
	return file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *WideTable) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WideTable) GetKind() TableKind {
	if x != nil {
		return x.Kind
	}
	return TableKind_TABLE_KIND_UNSPECIFIED
}

func (x *WideTable) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

func (x *WideTable) GetArrowIpc() []byte {
	if x != nil {
		return x.ArrowIpc
	}
	return nil
}

var File_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto protoreflect.FileDescriptor

const file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDesc = "" +
	"\n" +
	"Aexporter/datadogwideexporter/internal/widepb/wide_telemetry.proto\x12\x10datadog.evp.wide\"\xf6\x02\n" +
	"\x15WideTelemetryEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x121\n" +
	"\x15flush_window_start_ms\x18\a \x01(\x04R\x12flushWindowStartMs\x12-\n" +
	"\x13flush_window_end_ms\x18\b \x01(\x04R\x10flushWindowEndMs\x123\n" +
	"\x06tables\x18\t \x03(\v2\x1b.datadog.evp.wide.WideTableR\x06tables\x12E\n" +
	"\x04tags\x18\n" +
	" \x03(\v21.datadog.evp.wide.WideTelemetryEnvelope.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\tWideTable\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.datadog.evp.wide.TableKindR\x04kind\x12\x1f\n" +
	"\vschema_json\x18\x03 \x01(\tR\n" +
	"schemaJson\x12\x1b\n" +
	"\tarrow_ipc\x18\x04 \x01(\fR\barrowIpc*Z\n" +
	"\tTableKind\x12\x1a\n" +
	"\x16TABLE_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TABLE_KIND_AGGREGATED\x10\x01\x12\x16\n" +
	"\x12TABLE_KIND_SAMPLED\x10\x02BoZmgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogwideexporter/internal/widepb;widepbb\x06proto3"

var (
	file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDescOnce sync.Once
	file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDescData []byte
)

func file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDescGZIP() []byte {
	file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDescOnce.Do(func() {
		file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDesc), len(file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDesc)))
	})
	return file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDescData
}

var file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_goTypes = []any{
	(TableKind)(0),                // 0: datadog.evp.wide.TableKind
	(*WideTelemetryEnvelope)(nil), // 1: datadog.evp.wide.WideTelemetryEnvelope
	(*WideTable)(nil),             // 2: datadog.evp.wide.WideTable
	nil,                           // 3: datadog.evp.wide.WideTelemetryEnvelope.TagsEntry
}
var file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_depIdxs = []int32{
	2, // 0: datadog.evp.wide.WideTelemetryEnvelope.tables:type_name -> datadog.evp.wide.WideTable
	3, // 1: datadog.evp.wide.WideTelemetryEnvelope.tags:type_name -> datadog.evp.wide.WideTelemetryEnvelope.TagsEntry
	0, // 2: datadog.evp.wide.WideTable.kind:type_name -> datadog.evp.wide.TableKind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_init() }
func file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_init() {
	if File_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDesc), len(file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_goTypes,
		DependencyIndexes: file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_depIdxs,
		EnumInfos:         file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_enumTypes,
		MessageInfos:      file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_msgTypes,
	}.Build()
	File_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto = out.File
	file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_goTypes = nil
	file_exporter_datadogwideexporter_internal_widepb_wide_telemetry_proto_depIdxs = nil
}
