# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: batch/v1
kind: Job
metadata:
  name: appsec-node-otlp
  namespace: ddot-poc
  labels:
    app.kubernetes.io/part-of: ddot-products-poc
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: appsec-node-otlp
        app.kubernetes.io/part-of: ddot-products-poc
    spec:
      restartPolicy: Never
      containers:
        - name: workload
          image: ddot-appsec-node:poc
          imagePullPolicy: Never
          env:
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://collector.ddot-poc.svc.cluster.local:4318/v1/traces
